#!/usr/bin/env python3
"""
Emit a PRE-CONFIGURED copy of the iPad Scriptable script.

Why: typing a camera password on a tablet keyboard in front of the client is the
single most likely thing to go wrong on site. This bakes the settings in, so the
on-site procedure is "import file, tap Self-test, tap Log Donation" — no typing,
no settings screens, no chance of a typo.

Reads live values from SECRETS.local.md (gitignored) and writes:

    camera-access/ipad/Aperture.local.js      <- gitignored, CONTAINS THE PASSWORD

Transfer it to the iPad by AirDrop (or iCloud Drive > Scriptable). Never commit
it, never email it.

Usage:  python3 scripts/make-ipad-script.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "camera-access" / "ipad" / "aperture-pull.js"
TARGET = REPO / "camera-access" / "ipad" / "Aperture.local.js"
SECRETS = REPO / "SECRETS.local.md"

RELAY = "https://<vercel-app-host>/api/donate"
LOCATION = "Cul2vate, Ellington Ag Center"
SNAPSHOT_PATH = "/ISAPI/Streaming/channels/101/picture"


def main() -> None:
    if not SECRETS.exists():
        sys.exit(f"ERROR: {SECRETS.name} not found. It is gitignored — it must exist on this machine.")
    secrets = SECRETS.read_text()

    ip = re.search(r"LAN:\s*`(\d+\.\d+\.\d+\.\d+)`", secrets)
    creds = re.search(r"user\s+`([^`]+)`\s*/\s*pass\s+`([^`]+)`", secrets)
    if not ip or not creds:
        sys.exit("ERROR: could not read the camera IP / admin credentials out of SECRETS.local.md.")

    base, user, password = f"http://{ip.group(1)}", creds.group(1), creds.group(2)

    js = SOURCE.read_text()
    block = re.search(r"const CONFIG = \{.*?\n\};", js, re.S)
    if not block:
        sys.exit("ERROR: CONFIG block not found in aperture-pull.js.")

    configured = (
        "const CONFIG = {\n"
        f'  base: "{base}",\n'
        f'  user: "{user}",\n'
        f'  pass: "{password}",\n'
        f'  path: "{SNAPSHOT_PATH}",\n'
        f'  relay: "{RELAY}",\n'
        f'  exportUrl: "{RELAY.replace("/api/donate", "/api/export")}",\n'
        f'  voidUrl: "{RELAY.replace("/api/donate", "/api/void")}",\n'
        f'  location: "{LOCATION}",\n'
        "  maxPixels: 1600,\n"
        "};"
    )
    out = js[: block.start()] + configured + js[block.end():]

    header = (
        "// ============================================================\n"
        "// PRE-CONFIGURED BUILD — CONTAINS THE CAMERA PASSWORD.\n"
        "// Generated by scripts/make-ipad-script.py. Gitignored on purpose.\n"
        "// Do not commit, email, or post this file. Regenerate instead.\n"
        "// ============================================================\n"
    )
    TARGET.write_text(header + out)
    TARGET.chmod(0o600)

    # Fail loudly rather than hand over a file that would not work on site.
    check = TARGET.read_text()
    problems = []
    if f'base: "{base}"' not in check:
        problems.append("camera address not baked in")
    if 'pass: ""' in check:
        problems.append("password placeholder still empty")
    if RELAY not in check:
        problems.append("relay URL missing")
    if "buildDigestAuth" not in check:
        problems.append("digest auth code missing")
    if problems:
        sys.exit("ERROR: generated file is not usable: " + "; ".join(problems))

    # Refuse to hand over a build that is not actually runnable. `node --check` alone
    # has already let functionless files reach the device.
    import subprocess
    check = REPO / "scripts" / "check-ipad-script.sh"
    if check.exists():
        result = subprocess.run(["bash", str(check), str(TARGET)], capture_output=True, text=True)
        if result.returncode != 0:
            TARGET.unlink(missing_ok=True)
            sys.exit("ERROR: generated build failed verification (deleted):\n" + result.stdout + result.stderr)
        print("verified: " + result.stdout.strip().splitlines()[-1])

    print(f"wrote  {TARGET.relative_to(REPO)}  ({TARGET.stat().st_size // 1024} KB, mode 600)")
    print(f"  camera : {base}  user={user}  pass={'*' * len(password)}")
    print(f"  relay  : {RELAY}")
    print("\nAirDrop this file to the iPad, open it in Scriptable, rename to 'Aperture'.")
    print("It never prompts for settings — the on-site steps are import, Self-test, done.")


if __name__ == "__main__":
    main()
